from github import Github
import argparse

# import ossrelease modules
import conf

def parse_args():
    '''
    Parse the CLI options.
    '''
    # Define parser and set up basic options
    parser = argparse.ArgumentParser(description='Send email notification for release.')
    parser.add_argument('--salt-ver', help='Specify salt version to use in email')

    return parser.parse_args()

def main():
    args = parse_args()
    opts = conf.get_conf()

    repo = Github(opts['GITHUB_TOKEN']).get_repo('saltstack/salt')

    # create release
    # todo: make sure the tag we are about to create a release for already exists
    msg = "WARNING: The tarball generated by GitHub will not have the correct version information when using a version not ending in .0 . Please use the tarball generated by SaltStack instead. See issue #41847 for more information."
    repo.create_git_release(args.salt_ver, args.salt_ver, msg)
    release = repo.get_release(id=args.salt_ver)

    # todo: download pypi file
    ver = args.salt_ver.split('v')[-1]
    release.upload_asset('/tmp/salt-{0}.tar.gz'.format(ver))

    # todo: add verification the release was created

if __name__ == '__main__':
    main()
